"""
Module 3 - Playing a Video from a File
======================================

Same API as the webcam - just pass a file path instead of a camera index:
    cap = cv2.VideoCapture("video.mp4")

Useful properties:
    CAP_PROP_FPS, CAP_PROP_FRAME_COUNT, CAP_PROP_FRAME_WIDTH/HEIGHT,
    CAP_PROP_POS_FRAMES (current / seek position)

Keys while playing (--show):  q = quit, p = pause/resume, g = toggle grayscale

By default the sample video generated by ../assets/create_sample_images.py is used,
so this works offline. Headless run: prints properties and saves a contact
sheet of frames to outputs/video_frames.png.
"""

import sys
from pathlib import Path

import cv2

BASE_DIR = Path(__file__).resolve().parent
sys.path.append(str(BASE_DIR.parent / "assets"))
from create_sample_images import get_video_path  # noqa: E402
from cv_helpers import base_parser, make_grid, output_dir, save_image  # noqa: E402


def video_properties(cap):
    """Return a dict with the main properties of an opened video."""
    return {
        "fps": cap.get(cv2.CAP_PROP_FPS),
        "frames": int(cap.get(cv2.CAP_PROP_FRAME_COUNT)),
        "width": int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)),
        "height": int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)),
    }


def play(cap, fps):
    """Play the video in a window at (roughly) its real speed."""
    delay = max(int(1000 / (fps or 25)), 1)   # ms to wait between frames
    paused, gray = False, False
    while True:
        if not paused:
            ok, frame = cap.read()
            if not ok:                        # end of the video
                break
            if gray:
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            cv2.imshow("Video (q quit, p pause, g gray)", frame)
        key = cv2.waitKey(delay) & 0xFF
        if key == ord("q"):
            break
        if key == ord("p"):
            paused = not paused
        if key == ord("g"):
            gray = not gray
    cv2.destroyAllWindows()


def sample_frames(cap, n=6):
    """Seek to n evenly spaced positions and return (frames, titles)."""
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frames, titles = [], []
    for i in range(n):
        idx = int(i * (total - 1) / max(n - 1, 1))
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)     # jump directly to that frame
        ok, frame = cap.read()
        if ok:
            frames.append(frame)
            titles.append(f"frame {idx}")
    return frames, titles


if __name__ == "__main__":
    parser = base_parser("Play a video file")
    parser.add_argument("--video", type=Path, default=None,
                        help="path to a video (default: generated sample video)")
    args = parser.parse_args()

    video_path = args.video or get_video_path()
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print(f"Could not open video: {video_path}")
        sys.exit(1)

    props = video_properties(cap)
    print(f"Video: {video_path.name}")
    for k, v in props.items():
        print(f"  {k:<7}: {v}")
    if props["fps"]:
        print(f"  length : {props['frames'] / props['fps']:.1f} seconds")

    try:
        if args.show:
            play(cap, props["fps"])
        else:
            # Read the whole file once (what playback does) and count the frames
            count = 0
            while cap.read()[0]:
                count += 1
            print(f"Read {count} frames from the file (headless - no window).")
        frames, titles = sample_frames(cap)
        save_image(output_dir(__file__), "video_frames.png", make_grid(frames, titles, cols=3))
    finally:
        cap.release()
